name: IssueIsekai
version: "${version}"
main: ru.arzer0.issueisekai.plugin.IssueIsekaiPlugin
api-version: "26.1"
softdepend:
  - Denizen
commands:
  bugreport:
    description: Open the bug report dialog
    aliases:
      - bug
      - bugreprt
    permission: bugreport.submit
permissions:
  bugreport.submit:
    default: true
  bugreport.open.others:
    default: op
